### ISSUE TITLE
David doesn't respond to messages

### ISSUE THREAD

**Issue by Hadyn** [davidi2/mopar#33]
I think this could be fixed pretty easily.

**Comment by davidi2** [comment]
What message?

**Comment by zuppers** [comment]
Maybe if David would just idle in irc.

**Comment by Hadyn** [comment]
^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^


^^^^^^^^^^^^^

^^
^
^
^
^

I mean how hard is that

**Comment by davidi2** [comment]
With people like whacatre and pure and classic on IRC, harder than you think.

**Comment by Hadyn** [comment]
Lets make a new private channel then where we can talk. Ill pm you the details
